import React, { Fragment } from 'react'


export const About = () => (
    <Fragment>
    <h1>About</h1>
    <br/>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil natus quo sint quos voluptas iure harum, odit incidunt voluptatem, modi pariatur ea quas ipsum dolore, consequatur possimus facere! Sequi voluptates id cum dolor eligendi animi, exercitationem magni natus cumque quibusdam distinctio nesciunt eveniet nisi debitis placeat omnis ipsum itaque vitae? Voluptatum pariatur nam vero non rem tenetur eaque magni, odit facilis, voluptatem soluta eveniet, sint consectetur! Unde accusantium asperiores tempore quis itaque inventore, hic ipsum eveniet quam commodi facere totam quas labore blanditiis eius non in aliquam nihil voluptates aliquid cupiditate repudiandae eos? Ullam, optio numquam autem tenetur repellendus obcaecati!</p>
    <br/>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem culpa dolor inventore officiis ipsam ipsa, earum accusamus rerum, magnam, consectetur consequuntur! Sunt asperiores minus illo dolorem ipsam, totam assumenda magnam reiciendis modi dolor, libero laboriosam adipisci debitis aliquam? Inventore, assumenda aspernatur eaque vel pariatur similique ex sint voluptatibus, voluptas, quis rem mollitia molestias alias soluta perspiciatis magnam earum debitis consequuntur. Repudiandae blanditiis a odit distinctio facilis dignissimos explicabo aliquid numquam minima? Repellat facilis, ipsum laudantium sunt magni iusto a, necessitatibus vel omnis quis vero, optio quasi! Facere beatae cupiditate assumenda nihil, omnis iure accusantium quae dolorum officia deserunt ea quod inventore delectus! Eius beatae quia provident itaque, fugit nostrum cum harum, perferendis ab nemo adipisci quas labore commodi accusamus dolorem! Inventore, adipisci harum. In eos, magnam perspiciatis quisquam dolorem omnis blanditiis at aperiam ipsam? Deleniti ab minus autem, velit quas non dolorum corporis natus? Placeat vel quibusdam, expedita, quod tempore culpa harum earum saepe voluptatibus distinctio sunt deleniti eum labore dolorum porro eaque molestias, ea illo. Nisi voluptatibus commodi ipsum porro eveniet nam deleniti accusantium minus odit sit labore alias nemo, facere distinctio ducimus laudantium. Impedit vitae adipisci quia modi odit autem vero, saepe molestias optio aspernatur officia voluptatem corrupti?</p>
    </Fragment>
    );